name: Check Disk Space

on:
  push:
  workflow_dispatch:

jobs:
  check-disk:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check disk space
        run: df -h

      - name: Check subdirectory sizes
        run: |
          sudo du -hx -d1 /usr/local
          sudo du -hx -d1 /opt/hostedtoolcache

      - name: Check directory sizes
        run: |
          sudo du -hx -d1 /usr
          sudo du -hx -d1 /opt
